### ISSUE TITLE
About https://github.com/hadijomaa/HypRL.git.

### ISSUE THREAD

**Issue by Jessyca-ai** [hadijomaa/dataset2vec#1]
I was lucky to see your article Hyp-RL : Hyperparameter Optimization by Reinforcement Learning, I think this is a very meaningful idea, you gave a link https://github.com/hadijomaa/HypRL.git. But I can't see this in your popular repositories. Could you open source this?

**Comment by guochang013** [comment]
> I was lucky to see your article Hyp-RL : Hyperparameter Optimization by Reinforcement Learning, I think this is a very meaningful idea, you gave a link https://github.com/hadijomaa/HypRL.git. But I can't see this in your popular repositories. Could you open source this?

**Comment by hadijomaa** [comment]
Thank you for your interest in this project. I am currently updating that repo locally.
Please contact me via email for any questions regarding the paper.
