### ISSUE TITLE
Impossible to run ' python main.py '

### ISSUE THREAD

**Issue by legolasflagstaff** [hadijomaa/dataset2vec#2]
Hello, 

I would like to explore your software. 

However, when I run : pythonmain.py

Whether it be on Tensorflow1 or Tensorflow2 I get an error

In Tensorflow1 environment the error is:

```python 
TypeError: __init__() got an unexpected keyword argument 'n_values'
```

Are you planning on solving this issue or should I recode the paper myself?

Thanks, -MH

**Comment by hadijomaa** [comment]
Dear MH, 
my apologies for the super late reply. The code has went a drastic change. It has been updated to tensorflow v2+. 
If you are still interested in the package, you can try to run d2v.py. the main file, and let me know how it goes !

Hadi
